export const THEME_CHANGE = "THEME_CHANGE";

// USER AUTHENTICATION
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

// TOP TRACKS
export const FETCH_TOP_TRACKS_START = "FETCH_TOP_TRACKS_START";
export const FETCH_TOP_TRACKS_SUCCESS = "FETCH_TOP_TRACKS_SUCCESS";
export const FETCH_TOP_TRACKS_ERROR = "FETCH_TOP_TRACKS_ERROR";
